
- name: Create .config directory if it does not exist
  ansible.builtin.file:
    path: "{{ homedir }}/.config"
    state: directory
    mode: '0755'

- name: Create .config/nvim directory if it does not exist
  ansible.builtin.file:
    path: "{{ homedir }}/.config/nvim"
    state: directory
    mode: '0755'

- name: Copy nvim Lua config
  copy:
    src: "{{ role_path }}/files/nvim/init.lua"
    dest: "{{ homedir }}/.config/nvim/init.lua"
    owner: "{{ username }}"
    group: staff

- name: Check if nvim conf exists
  stat:
    path: "{{ homedir }}/.config/nvim"
  register: nvimconf

- name: Check if nvim colors exists
  stat:
    path: "{{ homedir }}/.config/nvim/colors/molokai.vim"
  register: nvimcolors

- name: Copy nvim confs
  copy:
    src: "{{ role_path }}/files/vim/"
    dest: "{{ homedir }}/.config/nvim"
    owner: "{{ username }}"
    group: staff
  when: not nvimcolors.stat.exists

- name: Copy /opt
  copy:
    src: "{{ role_path }}/files/opt"
    dest: "{{ homedir }}/"
    owner: "{{ username }}"
    group: staff
    mode: u+x

- name: Install global python packages
  ansible.builtin.pip:
    name:
      - black
      - jedi-language-server
      - flake8
      - flake8-isort
      - isort
      - pynvim
    extra_args: "-U"

- name: Check if pyenv conf exists
  stat:
    path: "{{ homedir }}/.pyenv"
  register: pyenvconf

- name: Install pyenv
  git:
    repo: https://github.com/pyenv/pyenv.git
    dest: "{{ homedir }}/.pyenv"
    update: no
  when: not pyenvconf.stat.exists

- name: Install pyenv-virtualenv
  git:
    repo: https://github.com/pyenv/pyenv-virtualenv.git
    dest: "{{ homedir }}/.pyenv/plugins/pyenv-virtualenv"
    update: no
  when: not pyenvconf.stat.exists

- name: Install oh-my-zsh
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  args:
    creates: "{{ homedir }}/.oh-my-zsh"

- name: Copy zshrc
  copy:
    src: "{{ role_path }}/files/zshrc"
    dest: "{{ homedir }}/.zshrc"
    owner: "{{ username }}"
    group: staff
