- name: Add Enpass repo key
  ansible.builtin.apt_key:
    url: https://apt.enpass.io/keys/enpass-linux.key
    state: present

- name: Ensure Enpass apt repo is present
  ansible.builtin.apt_repository:
    repo: "deb https://apt.enpass.io/ stable main"
    state: present
    update_cache: true

- name: Add Google Chrome signing key
  ansible.builtin.apt_key:
    url: "https://dl.google.com/linux/linux_signing_key.pub"
    state: present

- name: Add Google Chrome repository into sources list
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
    state: present
    filename: google-chrome

- name: Ensure Neovim PPA is present
  ansible.builtin.apt_repository:
    repo: ppa:neovim-ppa/stable

- name: Ensure OBS PPA is present
  ansible.builtin.apt_repository:
    repo: ppa:obsproject/obs-studio

- name: Install apt packages
  ansible.builtin.apt:
    pkg:
      - pipx
      - python3.8-venv
      - tmux
      - git
      - vlc
      - keychain
      - build-essential
      - wmctrl
      - gimp
      - neovim
      - rkhunter
      - zlib1g-dev
      - libffi-dev
      - libssl-dev
      - ffmpeg
      - v4l2loopback-dkms
      - obs-studio
      - fzf
      - awscli
      - enpass
